//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 29.11.2018 17:43:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace ToyoharaCore
{
    public partial class SYS_SELECT_LOGResult {

        public SYS_SELECT_LOGResult()
        {
            OnCreated();
        }

        public virtual string user_description
        {
            get;
            set;
        }

        public virtual string action_type
        {
            get;
            set;
        }

        public virtual string object_description
        {
            get;
            set;
        }

        public virtual string action_description
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> start_date
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> finish_date
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> file_date
        {
            get;
            set;
        }

        public virtual string file_description
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
