//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 29.11.2018 17:43:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace ToyoharaCore
{
    public partial class OMC_SELECT_SVRResult {

        public OMC_SELECT_SVRResult()
        {
            OnCreated();
        }

        public virtual int id
        {
            get;
            set;
        }

        public virtual string project_description
        {
            get;
            set;
        }

        public virtual System.DateTime creation_date
        {
            get;
            set;
        }

        public virtual string user_description
        {
            get;
            set;
        }

        public virtual System.Nullable<int> total_cnt
        {
            get;
            set;
        }

        public virtual System.Nullable<double> total_sum
        {
            get;
            set;
        }

        public virtual System.Nullable<int> error_cnt
        {
            get;
            set;
        }

        public virtual string last_version
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
