//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 29.11.2018 17:43:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace ToyoharaCore
{
    public partial class OMC_REPORT_FORM_SVR_SUBCONTRACTOR_ITEMSResult {

        public OMC_REPORT_FORM_SVR_SUBCONTRACTOR_ITEMSResult()
        {
            OnCreated();
        }

        public virtual int id
        {
            get;
            set;
        }

        public virtual string local_estimate_number
        {
            get;
            set;
        }

        public virtual string project_documentation_code
        {
            get;
            set;
        }

        public virtual string number
        {
            get;
            set;
        }

        public virtual string resource_code
        {
            get;
            set;
        }

        public virtual string ekk_code
        {
            get;
            set;
        }

        public virtual string description
        {
            get;
            set;
        }

        public virtual string unit_description
        {
            get;
            set;
        }

        public virtual System.Nullable<double> quantity
        {
            get;
            set;
        }

        public virtual System.Nullable<double> price
        {
            get;
            set;
        }

        public virtual System.Nullable<double> summa
        {
            get;
            set;
        }

        public virtual string turnover
        {
            get;
            set;
        }

        public virtual string phase
        {
            get;
            set;
        }

        public virtual decimal price1
        {
            get;
            set;
        }

        public virtual string supplier_description
        {
            get;
            set;
        }

        public virtual string delivery_base
        {
            get;
            set;
        }

        public virtual string price_source_number
        {
            get;
            set;
        }

        public virtual string comment
        {
            get;
            set;
        }

        public virtual string price_source_link
        {
            get;
            set;
        }

        public virtual string price_source
        {
            get;
            set;
        }

        public virtual int price_source_year
        {
            get;
            set;
        }

        public virtual decimal delivery_to_zhd_price
        {
            get;
            set;
        }

        public virtual decimal delivery_from_zhd_to_object_price
        {
            get;
            set;
        }

        public virtual decimal delivery_auto_to_object_price
        {
            get;
            set;
        }

        public virtual decimal prr_price
        {
            get;
            set;
        }

        public virtual decimal package_price
        {
            get;
            set;
        }

        public virtual decimal storage_price
        {
            get;
            set;
        }

        public virtual decimal total_price
        {
            get;
            set;
        }

        public virtual decimal summa1
        {
            get;
            set;
        }

        public virtual decimal total_summa
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
