//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 04.10.2018 17:27:30
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace ToyoharaCore
{
    public partial class UI_SELECT_GRID_SETTINGS2Result {

        public UI_SELECT_GRID_SETTINGS2Result()
        {
            OnCreated();
        }

        public virtual System.Nullable<bool> global_visible
        {
            get;
            set;
        }

        public virtual System.Nullable<bool> global_editable
        {
            get;
            set;
        }

        public virtual string field_description
        {
            get;
            set;
        }

        public virtual string russian_field_description
        {
            get;
            set;
        }

        public virtual System.Nullable<bool> is_visible
        {
            get;
            set;
        }

        public virtual System.Nullable<int> width
        {
            get;
            set;
        }

        public virtual System.Nullable<int> number
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
