//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 29.11.2018 17:43:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace ToyoharaCore
{
    public partial class APL_SELECT_PROJECT_REQUIREMENTSResult {

        public APL_SELECT_PROJECT_REQUIREMENTSResult()
        {
            OnCreated();
        }

        public virtual int id
        {
            get;
            set;
        }

        public virtual string code
        {
            get;
            set;
        }

        public virtual int object_description_id
        {
            get;
            set;
        }

        public virtual string object_description
        {
            get;
            set;
        }

        public virtual int subobject_id
        {
            get;
            set;
        }

        public virtual string subobject
        {
            get;
            set;
        }

        public virtual string subobject_font_color
        {
            get;
            set;
        }

        public virtual int ps_id
        {
            get;
            set;
        }

        public virtual string ps
        {
            get;
            set;
        }

        public virtual string ps_font_color
        {
            get;
            set;
        }

        public virtual int plno_id
        {
            get;
            set;
        }

        public virtual string plno
        {
            get;
            set;
        }

        public virtual string plno_font_color
        {
            get;
            set;
        }

        public virtual int project_documentation_id
        {
            get;
            set;
        }

        public virtual string project_documentation
        {
            get;
            set;
        }

        public virtual string project_documentation_font_color
        {
            get;
            set;
        }

        public virtual int revision_id
        {
            get;
            set;
        }

        public virtual System.Nullable<int> revision
        {
            get;
            set;
        }

        public virtual string description
        {
            get;
            set;
        }

        public virtual string description_font_color
        {
            get;
            set;
        }

        public virtual string package_contents
        {
            get;
            set;
        }

        public virtual string package_contents_font_color
        {
            get;
            set;
        }

        public virtual string additional_properties
        {
            get;
            set;
        }

        public virtual string additional_properties_font_color
        {
            get;
            set;
        }

        public virtual string manufacturer
        {
            get;
            set;
        }

        public virtual string manufacturer_font_color
        {
            get;
            set;
        }

        public virtual int unit_id
        {
            get;
            set;
        }

        public virtual string unit
        {
            get;
            set;
        }

        public virtual System.Nullable<double> quantity
        {
            get;
            set;
        }

        public virtual string quantity_font_color
        {
            get;
            set;
        }

        public virtual int main_prslno_id
        {
            get;
            set;
        }

        public virtual string prslno_total_info
        {
            get;
            set;
        }

        public virtual System.Nullable<double> mass_per_unit
        {
            get;
            set;
        }

        public virtual string mass_per_unit_font_color
        {
            get;
            set;
        }

        public virtual string mass_size
        {
            get;
            set;
        }

        public virtual string mass_size_font_color
        {
            get;
            set;
        }

        public virtual int item_state_id
        {
            get;
            set;
        }

        public virtual string item_state_description
        {
            get;
            set;
        }

        public virtual string reason_change_state
        {
            get;
            set;
        }

        public virtual System.Nullable<int> delivery_type_id
        {
            get;
            set;
        }

        public virtual string delivery_type
        {
            get;
            set;
        }

        public virtual string delivery_type_font_color
        {
            get;
            set;
        }

        public virtual System.Nullable<int> goods_type_id
        {
            get;
            set;
        }

        public virtual string goods_type
        {
            get;
            set;
        }

        public virtual string goods_type_font_color
        {
            get;
            set;
        }

        public virtual string summary
        {
            get;
            set;
        }

        public virtual string summary_font_color
        {
            get;
            set;
        }

        public virtual string summary2
        {
            get;
            set;
        }

        public virtual string summary2_font_color
        {
            get;
            set;
        }

        public virtual System.Nullable<int> in_kd_id
        {
            get;
            set;
        }

        public virtual string in_kd
        {
            get;
            set;
        }

        public virtual string in_kd_font_color
        {
            get;
            set;
        }

        public virtual System.Nullable<int> psd_state_id
        {
            get;
            set;
        }

        public virtual string psd_state
        {
            get;
            set;
        }

        public virtual string psd_state_font_color
        {
            get;
            set;
        }

        public virtual System.Nullable<int> pr_source_id
        {
            get;
            set;
        }

        public virtual string pr_source
        {
            get;
            set;
        }

        public virtual string pr_source_font_color
        {
            get;
            set;
        }

        public virtual System.DateTime creation_date
        {
            get;
            set;
        }

        public virtual System.DateTime modification_date
        {
            get;
            set;
        }

        public virtual string parent_package_code
        {
            get;
            set;
        }

        public virtual string ekk_code
        {
            get;
            set;
        }

        public virtual string drv_delivery_type
        {
            get;
            set;
        }

        public virtual string supply_manager
        {
            get;
            set;
        }

        public virtual string order_information
        {
            get;
            set;
        }

        public virtual string specification_information
        {
            get;
            set;
        }

        public virtual string change_history
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> start_delivery_date
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> finish_delivery_date
        {
            get;
            set;
        }

        public virtual string unsi_comment
        {
            get;
            set;
        }

        public virtual string dmtos_comment
        {
            get;
            set;
        }

        public virtual string color
        {
            get;
            set;
        }

        public virtual decimal delivered
        {
            get;
            set;
        }

        public virtual decimal not_delivered
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> deficit_delivery_date
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> fact_delivery_date
        {
            get;
            set;
        }

        public virtual string dks_customer_letter_info
        {
            get;
            set;
        }

        public virtual string edit_notes
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
