//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 29.11.2018 17:43:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace ToyoharaCore
{
    public partial class OMC_SELECT_FORM_SVR_ITEMS_ADDEDResult {

        public OMC_SELECT_FORM_SVR_ITEMS_ADDEDResult()
        {
            OnCreated();
        }

        public virtual int id
        {
            get;
            set;
        }

        public virtual string local_estimate_number
        {
            get;
            set;
        }

        public virtual string project_documentation_code
        {
            get;
            set;
        }

        public virtual string number
        {
            get;
            set;
        }

        public virtual string resource_code
        {
            get;
            set;
        }

        public virtual string ekk_code
        {
            get;
            set;
        }

        public virtual System.Nullable<int> price_manager_id
        {
            get;
            set;
        }

        public virtual string price_manager_description
        {
            get;
            set;
        }

        public virtual string description
        {
            get;
            set;
        }

        public virtual int unit_id
        {
            get;
            set;
        }

        public virtual string unit_description
        {
            get;
            set;
        }

        public virtual System.Nullable<double> quantity
        {
            get;
            set;
        }

        public virtual System.Nullable<double> price
        {
            get;
            set;
        }

        public virtual System.Nullable<double> summa
        {
            get;
            set;
        }

        public virtual string turnover
        {
            get;
            set;
        }

        public virtual string phase
        {
            get;
            set;
        }

        public virtual string svr_delivery_type
        {
            get;
            set;
        }

        public virtual string add_info
        {
            get;
            set;
        }

        public virtual System.Nullable<int> delivery_type_id
        {
            get;
            set;
        }

        public virtual string delivery_type_description
        {
            get;
            set;
        }

        public virtual string unsi_comment
        {
            get;
            set;
        }

        public virtual string dmtos_comment
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> commit_changes_date
        {
            get;
            set;
        }

        public virtual string for_pricing
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
