//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 29.11.2018 17:43:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace ToyoharaCore
{
    public partial class OMC_SELECT_FORM_RSS_ITEMS_DIFFResult {

        public OMC_SELECT_FORM_RSS_ITEMS_DIFFResult()
        {
            OnCreated();
        }

        public virtual string id
        {
            get;
            set;
        }

        public virtual System.Nullable<int> form_item_id
        {
            get;
            set;
        }

        public virtual int prslno_id
        {
            get;
            set;
        }

        public virtual System.Nullable<int> form_id
        {
            get;
            set;
        }

        public virtual int project_id
        {
            get;
            set;
        }

        public virtual string diff_type
        {
            get;
            set;
        }

        public virtual string code
        {
            get;
            set;
        }

        public virtual string last_object_description
        {
            get;
            set;
        }

        public virtual string new_object_description
        {
            get;
            set;
        }

        public virtual string color_object_description
        {
            get;
            set;
        }

        public virtual string last_subobject_description
        {
            get;
            set;
        }

        public virtual string new_subobject_description
        {
            get;
            set;
        }

        public virtual string color_subobject_description
        {
            get;
            set;
        }

        public virtual string last_subcontractor_description
        {
            get;
            set;
        }

        public virtual string new_subcontractor_description
        {
            get;
            set;
        }

        public virtual string color_subcontractor_description
        {
            get;
            set;
        }

        public virtual string last_lno_description
        {
            get;
            set;
        }

        public virtual string new_lno_description
        {
            get;
            set;
        }

        public virtual string color_lno_description
        {
            get;
            set;
        }

        public virtual string last_project_documentation_code
        {
            get;
            set;
        }

        public virtual string new_project_documentation_code
        {
            get;
            set;
        }

        public virtual string color_project_documentation_code
        {
            get;
            set;
        }

        public virtual System.Nullable<int> last_revision_number
        {
            get;
            set;
        }

        public virtual System.Nullable<int> new_revision_number
        {
            get;
            set;
        }

        public virtual string color_revision_number
        {
            get;
            set;
        }

        public virtual string last_description
        {
            get;
            set;
        }

        public virtual string new_description
        {
            get;
            set;
        }

        public virtual string color_description
        {
            get;
            set;
        }

        public virtual string last_additional_properties
        {
            get;
            set;
        }

        public virtual string new_additional_properties
        {
            get;
            set;
        }

        public virtual string color_additional_properties
        {
            get;
            set;
        }

        public virtual string last_package_contents
        {
            get;
            set;
        }

        public virtual string new_package_contents
        {
            get;
            set;
        }

        public virtual string color_package_contents
        {
            get;
            set;
        }

        public virtual string last_manufacturer
        {
            get;
            set;
        }

        public virtual string new_manufacturer
        {
            get;
            set;
        }

        public virtual string color_manufacturer
        {
            get;
            set;
        }

        public virtual string last_unit_description
        {
            get;
            set;
        }

        public virtual string new_unit_description
        {
            get;
            set;
        }

        public virtual string color_unit_description
        {
            get;
            set;
        }

        public virtual System.Nullable<double> last_quantity
        {
            get;
            set;
        }

        public virtual System.Nullable<double> new_quantity
        {
            get;
            set;
        }

        public virtual string color_quantity
        {
            get;
            set;
        }

        public virtual System.Nullable<double> last_mass_per_unit
        {
            get;
            set;
        }

        public virtual System.Nullable<double> new_mass_per_unit
        {
            get;
            set;
        }

        public virtual string color_mass_per_unit
        {
            get;
            set;
        }

        public virtual string last_mass_size
        {
            get;
            set;
        }

        public virtual string new_mass_size
        {
            get;
            set;
        }

        public virtual string color_mass_size
        {
            get;
            set;
        }

        public virtual string last_summary
        {
            get;
            set;
        }

        public virtual string new_summary
        {
            get;
            set;
        }

        public virtual string color_summary
        {
            get;
            set;
        }

        public virtual string last_summary2
        {
            get;
            set;
        }

        public virtual string new_summary2
        {
            get;
            set;
        }

        public virtual string color_summary2
        {
            get;
            set;
        }

        public virtual string last_project_requirement_source
        {
            get;
            set;
        }

        public virtual string new_project_requirement_source
        {
            get;
            set;
        }

        public virtual string color_project_requirement_source
        {
            get;
            set;
        }

        public virtual string last_delivery_type_description
        {
            get;
            set;
        }

        public virtual string new_delivery_type_description
        {
            get;
            set;
        }

        public virtual string color_delivery_type_description
        {
            get;
            set;
        }

        public virtual string last_project_requirement_state_description
        {
            get;
            set;
        }

        public virtual string new_project_requirement_state_description
        {
            get;
            set;
        }

        public virtual string color_project_requirement_state_description
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
