//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 29.11.2018 17:43:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace ToyoharaCore
{
    public partial class UI_SELECT_MAIL_NOTIFICATIONSResult {

        public UI_SELECT_MAIL_NOTIFICATIONSResult()
        {
            OnCreated();
        }

        public virtual int id
        {
            get;
            set;
        }

        public virtual System.Nullable<int> section_id
        {
            get;
            set;
        }

        public virtual string section
        {
            get;
            set;
        }

        public virtual string description
        {
            get;
            set;
        }

        public virtual string mail_subject
        {
            get;
            set;
        }

        public virtual string summary
        {
            get;
            set;
        }

        public virtual string schedule_period
        {
            get;
            set;
        }

        public virtual string schedule_time
        {
            get;
            set;
        }

        public virtual string mail_list
        {
            get;
            set;
        }

        public virtual string stored_procedure
        {
            get;
            set;
        }

        public virtual string template_file
        {
            get;
            set;
        }

        public virtual string modification_user
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> modification_date
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
