//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 29.10.2018 9:10:23
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace ToyoharaCore
{
    public partial class OMC_SELECT_FORM_RSS_ITEMSResult {

        public OMC_SELECT_FORM_RSS_ITEMSResult()
        {
            OnCreated();
        }

        public virtual int id
        {
            get;
            set;
        }

        public virtual System.Nullable<int> form_id
        {
            get;
            set;
        }

        public virtual string code
        {
            get;
            set;
        }

        public virtual string object_description
        {
            get;
            set;
        }

        public virtual string subobject_description
        {
            get;
            set;
        }

        public virtual int subcontractor_id
        {
            get;
            set;
        }

        public virtual string subcontractor_description
        {
            get;
            set;
        }

        public virtual int lno_id
        {
            get;
            set;
        }

        public virtual string lno_description
        {
            get;
            set;
        }

        public virtual string project_documentation_code
        {
            get;
            set;
        }

        public virtual System.Nullable<int> revision_number
        {
            get;
            set;
        }

        public virtual string ekk_code
        {
            get;
            set;
        }

        public virtual System.Nullable<int> price_manager_id
        {
            get;
            set;
        }

        public virtual string price_manager_description
        {
            get;
            set;
        }

        public virtual string description
        {
            get;
            set;
        }

        public virtual string additional_properties
        {
            get;
            set;
        }

        public virtual string package_contents
        {
            get;
            set;
        }

        public virtual string manufacturer
        {
            get;
            set;
        }

        public virtual int unit_id
        {
            get;
            set;
        }

        public virtual string unit_description
        {
            get;
            set;
        }

        public virtual System.Nullable<double> quantity
        {
            get;
            set;
        }

        public virtual System.Nullable<double> mass_per_unit
        {
            get;
            set;
        }

        public virtual string mass_size
        {
            get;
            set;
        }

        public virtual string summary
        {
            get;
            set;
        }

        public virtual string summary2
        {
            get;
            set;
        }

        public virtual string project_requirement_source
        {
            get;
            set;
        }

        public virtual string delivery_type_description
        {
            get;
            set;
        }

        public virtual System.Nullable<int> suggested_delivery_type_id
        {
            get;
            set;
        }

        public virtual string suggested_delivery_type_description
        {
            get;
            set;
        }

        public virtual System.Nullable<int> delivery_type_id
        {
            get;
            set;
        }

        public virtual string delivery_type_description1
        {
            get;
            set;
        }

        public virtual string unsi_comment
        {
            get;
            set;
        }

        public virtual string dmtos_comment
        {
            get;
            set;
        }

        public virtual string chanhes_info
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> commit_changes_date
        {
            get;
            set;
        }

        public virtual int project_requirement_state_id
        {
            get;
            set;
        }

        public virtual string project_requirement_state_description
        {
            get;
            set;
        }

        public virtual string for_pricing
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
