//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 29.10.2018 9:10:23
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ToyoharaCore
{
    public partial class APL_SELECT_PROJECT_LOGISTICAL_NETWORK_OBJECTSResult {

        public APL_SELECT_PROJECT_LOGISTICAL_NETWORK_OBJECTSResult()
        {
            OnCreated();
        }        
        public virtual int id
        {
            get;
            set;
        }

        public virtual int lno_id
        {
            get;
            set;
        }

        public virtual string lno_description
        {
            get;
            set;
        }

        public virtual double start
        {
            get;
            set;
        }

        public virtual System.Nullable<double> finish
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
