//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 29.11.2018 17:43:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace ToyoharaCore
{
    public partial class NPS_SELECT_RESERVATION_ORDER_ITEMSResult {

        public NPS_SELECT_RESERVATION_ORDER_ITEMSResult()
        {
            OnCreated();
        }

        public virtual int id
        {
            get;
            set;
        }

        public virtual string nps_code
        {
            get;
            set;
        }

        public virtual string nom_code
        {
            get;
            set;
        }

        public virtual string nom_description
        {
            get;
            set;
        }

        public virtual string storage_description
        {
            get;
            set;
        }

        public virtual System.Nullable<double> stock_price
        {
            get;
            set;
        }

        public virtual System.Nullable<double> stock_summa
        {
            get;
            set;
        }

        public virtual string stock_unit
        {
            get;
            set;
        }

        public virtual System.Nullable<double> stock_quantity
        {
            get;
            set;
        }

        public virtual System.Nullable<double> prslno_quantity
        {
            get;
            set;
        }

        public virtual string prslno_unit
        {
            get;
            set;
        }

        public virtual string prslno_code
        {
            get;
            set;
        }

        public virtual string prslno_description
        {
            get;
            set;
        }

        public virtual System.Nullable<double> base_estimate_price
        {
            get;
            set;
        }

        public virtual System.Nullable<double> base_estimate_summa
        {
            get;
            set;
        }

        public virtual System.Nullable<double> estimate_price_coefficient
        {
            get;
            set;
        }

        public virtual System.Nullable<double> estimate_summa
        {
            get;
            set;
        }

        public virtual string estimate_state
        {
            get;
            set;
        }

        public virtual string lno
        {
            get;
            set;
        }

        public virtual string summary
        {
            get;
            set;
        }

        public virtual string prslno_project
        {
            get;
            set;
        }

        public virtual System.Nullable<double> quantity_fact
        {
            get;
            set;
        }

        public virtual System.Nullable<double> quantity_with_quality_approve
        {
            get;
            set;
        }

        public virtual System.Nullable<double> quantity_for_inspection
        {
            get;
            set;
        }

        public virtual System.Nullable<double> additional_costs
        {
            get;
            set;
        }

        public virtual System.Nullable<double> inspection_costs
        {
            get;
            set;
        }

        public virtual System.Nullable<double> keep_costs
        {
            get;
            set;
        }

        public virtual System.Nullable<double> dispatched
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> dispatched_date
        {
            get;
            set;
        }

        public virtual System.Nullable<double> delivered
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> delivered_date
        {
            get;
            set;
        }

        public virtual System.Nullable<double> sold
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> sold_date
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
