//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 29.11.2018 17:43:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace ToyoharaCore
{
    public partial class APL_SELECT_OBJECTS_AND_SUBOBJECTSResult {

        public APL_SELECT_OBJECTS_AND_SUBOBJECTSResult()
        {
            OnCreated();
        }

        public virtual int id
        {
            get;
            set;
        }

        public virtual System.Nullable<int> parent_id
        {
            get;
            set;
        }

        public virtual string description
        {
            get;
            set;
        }

        public virtual System.Nullable<double> start
        {
            get;
            set;
        }

        public virtual System.Nullable<double> finish
        {
            get;
            set;
        }

        public virtual string tree_errors
        {
            get;
            set;
        }

        public virtual string subcontractor_list
        {
            get;
            set;
        }

        public virtual string project_1c_guid
        {
            get;
            set;
        }

        public virtual string project_1c
        {
            get;
            set;
        }

        public virtual int is_parent
        {
            get;
            set;
        }

        public virtual int object_id
        {
            get;
            set;
        }

        public virtual string object_description
        {
            get;
            set;
        }

        public virtual string project_description
        {
            get;
            set;
        }

        public virtual int outline_level
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
