//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 29.10.2018 9:10:23
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace ToyoharaCore
{
    public partial class APL_SELECT_PROJECT_LIST_INFO2Result {

        public APL_SELECT_PROJECT_LIST_INFO2Result()
        {
            OnCreated();
        }

        public virtual int id
        {
            get;
            set;
        }

        public virtual string code
        {
            get;
            set;
        }

        public virtual string project_short_description
        {
            get;
            set;
        }

        public virtual string project_description
        {
            get;
            set;
        }

        public virtual int project_type_id
        {
            get;
            set;
        }

        public virtual string project_type
        {
            get;
            set;
        }

        public virtual int project_state_id
        {
            get;
            set;
        }

        public virtual string project_state
        {
            get;
            set;
        }

        public virtual string logistical_network_objects
        {
            get;
            set;
        }

        public virtual string subcontractors
        {
            get;
            set;
        }

        public virtual System.Nullable<int> customer_id
        {
            get;
            set;
        }

        public virtual string customer
        {
            get;
            set;
        }

        public virtual System.Nullable<int> designer_id
        {
            get;
            set;
        }

        public virtual string designer
        {
            get;
            set;
        }

        public virtual System.Nullable<double> start
        {
            get;
            set;
        }

        public virtual System.Nullable<double> finish
        {
            get;
            set;
        }

        public virtual System.Nullable<int> year1
        {
            get;
            set;
        }

        public virtual System.Nullable<int> year2
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> finish_date
        {
            get;
            set;
        }

        public virtual System.Nullable<int> build_curator_id
        {
            get;
            set;
        }

        public virtual string build_curator
        {
            get;
            set;
        }

        public virtual string build_curator_list_id
        {
            get;
            set;
        }

        public virtual string build_curator_list
        {
            get;
            set;
        }

        public virtual System.Nullable<int> package_curator_id
        {
            get;
            set;
        }

        public virtual string package_curator
        {
            get;
            set;
        }

        public virtual System.Nullable<int> supply_curator_id
        {
            get;
            set;
        }

        public virtual string supply_curator
        {
            get;
            set;
        }

        public virtual string supply_curator_list_id
        {
            get;
            set;
        }

        public virtual string supply_curator_list
        {
            get;
            set;
        }

        public virtual string deliveryplan_curator_list_id
        {
            get;
            set;
        }

        public virtual string deliveryplan_curator_list
        {
            get;
            set;
        }

        public virtual System.Nullable<int> project_curator_id
        {
            get;
            set;
        }

        public virtual string project_curator
        {
            get;
            set;
        }

        public virtual System.Nullable<int> stocks_curator_id
        {
            get;
            set;
        }

        public virtual string stocks_curator
        {
            get;
            set;
        }

        public virtual System.Nullable<int> normative_delivery_time
        {
            get;
            set;
        }

        public virtual string storage_contract
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> storage_contract_finish_date
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> build_start_date
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> build_finish_date
        {
            get;
            set;
        }

        public virtual System.Nullable<bool> non_project_supplier_approve_required
        {
            get;
            set;
        }

        public virtual System.Nullable<int> rss_match_type_id
        {
            get;
            set;
        }

        public virtual string rss_match_type
        {
            get;
            set;
        }

        public virtual System.Nullable<int> tpsu_division_id
        {
            get;
            set;
        }

        public virtual string tpsu_division
        {
            get;
            set;
        }

        public virtual string subcontractor_info_list_id
        {
            get;
            set;
        }

        public virtual string subcontractor_info_list
        {
            get;
            set;
        }

        public virtual string is_documentation_percent
        {
            get;
            set;
        }

        public virtual string is_documentation
        {
            get;
            set;
        }

        public virtual string is_change_documentation_percent
        {
            get;
            set;
        }

        public virtual string is_change_documentation
        {
            get;
            set;
        }

        public virtual string total_sum_gk
        {
            get;
            set;
        }

        public virtual string total_sum_direct
        {
            get;
            set;
        }

        public virtual string advance_info
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
