//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 29.10.2018 9:10:23
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace ToyoharaCore
{
    public partial class OMC_SELECT_FORMSResult {

        public OMC_SELECT_FORMSResult()
        {
            OnCreated();
        }

        public virtual int id
        {
            get;
            set;
        }

        public virtual int form_id
        {
            get;
            set;
        }

        public virtual string form_description
        {
            get;
            set;
        }

        public virtual int project_id
        {
            get;
            set;
        }

        public virtual string project_description
        {
            get;
            set;
        }

        public virtual System.DateTime modification_date
        {
            get;
            set;
        }

        public virtual string owner_description
        {
            get;
            set;
        }

        public virtual int total_cnt
        {
            get;
            set;
        }

        public virtual int total_diff
        {
            get;
            set;
        }

        public virtual int unsi_declined
        {
            get;
            set;
        }

        public virtual int dmtos_declined
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
