//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 29.11.2018 17:43:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace ToyoharaCore
{
    public partial class NPS_SELECT_RESERVATION_ORDERS2Result {

        public NPS_SELECT_RESERVATION_ORDERS2Result()
        {
            OnCreated();
        }

        public virtual int id
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> order_date
        {
            get;
            set;
        }

        public virtual string order_state
        {
            get;
            set;
        }

        public virtual string order_state_comment
        {
            get;
            set;
        }

        public virtual System.Nullable<int> items_cnt
        {
            get;
            set;
        }

        public virtual System.Nullable<double> items_sum
        {
            get;
            set;
        }

        public virtual string project_list
        {
            get;
            set;
        }

        public virtual string ekk_code
        {
            get;
            set;
        }

        public virtual string delivery_route
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
