//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 29.11.2018 17:43:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace ToyoharaCore
{
    public partial class SYS_SELECT_OBJECT_LOGResult {

        public SYS_SELECT_OBJECT_LOGResult()
        {
            OnCreated();
        }

        public virtual int id
        {
            get;
            set;
        }

        public virtual string object_type
        {
            get;
            set;
        }

        public virtual System.Nullable<int> object_id
        {
            get;
            set;
        }

        public virtual string object_description
        {
            get;
            set;
        }

        public virtual string action_type
        {
            get;
            set;
        }

        public virtual string action_description
        {
            get;
            set;
        }

        public virtual System.DateTime action_date
        {
            get;
            set;
        }

        public virtual int action_user_id
        {
            get;
            set;
        }

        public virtual string action_user
        {
            get;
            set;
        }

        public virtual System.Nullable<int> action_real_user_id
        {
            get;
            set;
        }

        public virtual string action_real_user
        {
            get;
            set;
        }

        public virtual string attribute
        {
            get;
            set;
        }

        public virtual string last_value
        {
            get;
            set;
        }

        public virtual string new_value
        {
            get;
            set;
        }

        public virtual string add_attr_last_value
        {
            get;
            set;
        }

        public virtual string add_attr_new_value
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
