//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 29.10.2018 9:10:23
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace ToyoharaCore
{
    public partial class OMC_SELECT_FORM_SVR_ITEMS_DIFFResult {

        public OMC_SELECT_FORM_SVR_ITEMS_DIFFResult()
        {
            OnCreated();
        }

        public virtual string id
        {
            get;
            set;
        }

        public virtual System.Nullable<int> fi_id
        {
            get;
            set;
        }

        public virtual System.Nullable<int> si_id
        {
            get;
            set;
        }

        public virtual System.Nullable<int> form_id
        {
            get;
            set;
        }

        public virtual System.Nullable<int> svr_id
        {
            get;
            set;
        }

        public virtual string diff_type
        {
            get;
            set;
        }

        public virtual string local_estimate_number
        {
            get;
            set;
        }

        public virtual string project_documentation_code
        {
            get;
            set;
        }

        public virtual string number
        {
            get;
            set;
        }

        public virtual string resource_code
        {
            get;
            set;
        }

        public virtual string description
        {
            get;
            set;
        }

        public virtual string last_unit_description
        {
            get;
            set;
        }

        public virtual string new_unit_description
        {
            get;
            set;
        }

        public virtual System.Nullable<double> last_quantity
        {
            get;
            set;
        }

        public virtual string new_quantity
        {
            get;
            set;
        }

        public virtual System.Nullable<double> last_price
        {
            get;
            set;
        }

        public virtual System.Nullable<double> new_price
        {
            get;
            set;
        }

        public virtual System.Nullable<double> last_summa
        {
            get;
            set;
        }

        public virtual System.Nullable<double> new_summa
        {
            get;
            set;
        }

        public virtual string last_turnover
        {
            get;
            set;
        }

        public virtual string new_turnover
        {
            get;
            set;
        }

        public virtual string last_svr_delivery_type
        {
            get;
            set;
        }

        public virtual string new_svr_delivery_type
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
