//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 29.11.2018 17:43:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace ToyoharaCore
{
    public partial class APL_SELECT_PROJECT_REQUIREMENTS_TOTAL_INFO2Result {

        public APL_SELECT_PROJECT_REQUIREMENTS_TOTAL_INFO2Result()
        {
            OnCreated();
        }

        public virtual int id
        {
            get;
            set;
        }

        public virtual string code
        {
            get;
            set;
        }

        public virtual string object_description
        {
            get;
            set;
        }

        public virtual string subobject_description
        {
            get;
            set;
        }

        public virtual string subcontractor
        {
            get;
            set;
        }

        public virtual string station
        {
            get;
            set;
        }

        public virtual string project_documentation
        {
            get;
            set;
        }

        public virtual string revision_number
        {
            get;
            set;
        }

        public virtual string description
        {
            get;
            set;
        }

        public virtual string package_content
        {
            get;
            set;
        }

        public virtual string additional_properties
        {
            get;
            set;
        }

        public virtual string manufacturer
        {
            get;
            set;
        }

        public virtual string unit
        {
            get;
            set;
        }

        public virtual System.Nullable<double> quantity
        {
            get;
            set;
        }

        public virtual string mass_size
        {
            get;
            set;
        }

        public virtual string item_state
        {
            get;
            set;
        }

        public virtual string reason_change_state
        {
            get;
            set;
        }

        public virtual string delivery_type
        {
            get;
            set;
        }

        public virtual string goods_type
        {
            get;
            set;
        }

        public virtual string in_kd_description
        {
            get;
            set;
        }

        public virtual string psd_state_description
        {
            get;
            set;
        }

        public virtual string pr_source_description
        {
            get;
            set;
        }

        public virtual string color
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
